import { NextResponse } from "next/server";
import { z } from "zod";
import { readFile, writeFile, rm, mkdtemp } from "fs/promises";
import { tmpdir } from "os";
import path from "path";
import { query } from "@/lib/db";
import { getOrCreateLocalUserId } from "@/lib/local-user";
import { VoiceoverRequestSchema } from "@/lib/schemas/voiceover";
import { getProvider } from "@/lib/ai/registry";
import { getDefaultSpeechModelId } from "@/lib/ai/default-models";
import { resolveCredential } from "@/lib/credentials/resolve-credential";
import { saveAsset } from "@/lib/storage/local-storage";
import { probeMedia } from "@/lib/media/ffmpeg";

const ProjectIdSchema = z.string().uuid();

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const userId = await getOrCreateLocalUserId();
  const { id } = await params;
  const parsedId = ProjectIdSchema.safeParse(id);
  if (!parsedId.success) {
    return NextResponse.json({ error: "Invalid project id." }, { status: 400 });
  }

  const [project] = await query<{ id: string }>(`select id from projects where id = $1 and user_id = $2`, [
    parsedId.data,
    userId,
  ]);
  if (!project) {
    return NextResponse.json({ error: "Project not found." }, { status: 404 });
  }

  const body = await request.json().catch(() => null);
  const parsed = VoiceoverRequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid input." }, { status: 400 });
  }
  const { connectionId, script } = parsed.data;

  const credential = await resolveCredential(connectionId, userId);
  if (!credential) {
    return NextResponse.json({ error: "That provider connection isn't available. Reconnect it and try again." }, { status: 422 });
  }

  const provider = getProvider(credential.provider);
  if (!provider.synthesizeSpeech) {
    return NextResponse.json({ error: "This provider doesn't support speech synthesis." }, { status: 422 });
  }

  try {
    const speech = await provider.synthesizeSpeech(
      { text: script, modelId: getDefaultSpeechModelId(credential.provider) },
      credential
    );

    // Two supported shapes for audioUrl: a data: URL (the real OpenAI
    // adapter -- raw generated bytes, base64-encoded, no filesystem side
    // effect in the adapter itself), or a same-origin static asset path
    // (the Mock Provider's /mock-assets/... placeholder).
    //
    // audioUrl comes from a provider adapter, not the requesting user
    // directly -- but a misbehaving or future adapter is still an
    // untrusted boundary. For the path form, resolve and require true
    // containment within public/, the same defense-in-depth pattern as
    // resolveStoragePath.
    const dataUrlMatch = /^data:audio\/[\w.+-]+;base64,(.+)$/i.exec(speech.audioUrl);
    let buffer: Buffer;
    if (dataUrlMatch) {
      buffer = Buffer.from(dataUrlMatch[1], "base64");
      if (buffer.length === 0) {
        return NextResponse.json({ error: "The generated voiceover audio was empty." }, { status: 502 });
      }
    } else {
      const publicRoot = path.join(process.cwd(), "public");
      const resolvedAudioPath = path.resolve(publicRoot, `.${speech.audioUrl}`);
      if (
        !speech.audioUrl.startsWith("/") ||
        (resolvedAudioPath !== publicRoot && !resolvedAudioPath.startsWith(publicRoot + path.sep))
      ) {
        return NextResponse.json({ error: "This provider's speech output isn't supported yet." }, { status: 501 });
      }
      buffer = await readFile(resolvedAudioPath);
    }

    // ffprobe needs a real file on disk, not a Buffer -- write to a scratch
    // temp dir just for the probe, cleaned up immediately after.
    const probeDir = await mkdtemp(path.join(tmpdir(), "clippn-voiceover-"));
    let durationSeconds: number;
    try {
      const probePath = path.join(probeDir, "voiceover.mp3");
      await writeFile(probePath, buffer);
      durationSeconds = (await probeMedia(probePath)).durationSeconds;
    } finally {
      await rm(probeDir, { recursive: true, force: true });
    }

    const saved = await saveAsset(parsedId.data, buffer, "voiceover.mp3");
    const [asset] = await query<{
      id: string;
      kind: string;
      storage_path: string;
      original_filename: string | null;
      duration_seconds: string | null;
    }>(
      `insert into assets
         (user_id, project_id, kind, storage_path, original_filename, mime_type, byte_size,
          duration_seconds, source)
       values ($1, $2, 'voiceover', $3, 'voiceover.mp3', 'audio/mpeg', $4, $5, 'generated')
       returning id, kind, storage_path, original_filename, duration_seconds`,
      [userId, parsedId.data, saved.storagePath, buffer.length, durationSeconds]
    );

    return NextResponse.json({ asset, mock: speech.mock === true });
  } catch (error) {
    const normalized = provider.normalizeError(error);
    return NextResponse.json({ error: normalized.message, category: normalized.category }, { status: 422 });
  }
}
